### ISSUE TITLE
Lage scripts for å slette og opprette rapporter automatisk

### ISSUE THREAD

**Issue by bjorn-iversen** [knowit/Dataplattform#458]
Akkurat nå så eksisterer rapportene bare som lagrede data. Vi burde skrive scripts som er versjonskontrollert som kan opprette og slette rapporter ved behov.

**Comment by kjell-r** [comment]
Lagt til utility update.py i /packages/cli/dataplattform/cli/commands/reports/. Kjør med --help for oversikt over parametre. Definisjoner for rapporter for dev og prod ligger nå under data/api.new-dev.json  og data/api.prod.json.
