### ISSUE TITLE
Kundeansvarlig for hvert kundeteam

### ISSUE THREAD

**Issue by torjohannessen** [knowit/Dataplattform#460]
# Oppgavebeskrivelse

Vi ønsker å ha en kundeansvarlig person for hvert Kundeteam/prosjekt.
Denne informasjonen har vi ikke, men lager et google regneark hvor vi setter opp Kunde-prosjket/-team og hvem som har rollen. Salg har et regneark som vi kan hente data fra: 
https://docs.google.com/spreadsheets/d/1_o0dqdeA2vZaQjFC0pGc8Csn1tOkREKq/edit#gid=84266779
Her er det snakk om kolonne A og L.
Dette gjøres på samme måte som Remapping knowit/Dataplattform-issues#541.

Resultat av importen ender i en fil i S3 som et endepunkt, Så kan Folk-app plukke opp dataene etterpå.

**Comment by kjell-r** [comment]
Så langt kommer det nye data inn i rapport når eier TJO kjører plugin i google sheet på nytt. Ser ikke ut som om det kjøres noe periodisk som tar inn endringer. Så det må kanskje opprettes en ny sak på det. Lukker denne saken, siden man nå kan ta i bruk dette i applikasjonen folk.
