### ISSUE TITLE
Dataplatform lambda som henter kompetansekartlegging data henter ikke ferske data

### ISSUE THREAD

**Issue by torjohannessen** [knowit/Dataplattform#525]
Det ser ut til at lambda funksjon som henter data fra kompetansekartlegging ikek henter nye kataloger eller nye svar.
Ser ut til at det ikke er noen log fra lambda funksjonen, men det er noe som ikke gir oppdaterte data.

**Comment by kjell-r** [comment]
I prod-miljøet ser det ut til at ingest går okay, og at process plukker opp fra sqs og så timer ut på 200ish sekunder. Jeg prøvde å endre timeout på kompetansekartlegging process manuelt, og da kommer det nye data i s3-bucket. Det må da trolig sjekkes inn en kode-endring i serverless.yml for kompetansekartlegging, feks endre til
